### ISSUE TITLE
Allow compilation with latest dependencies from conda-forge

### ISSUE THREAD

**Issue by shenker** [maickrau/GraphAligner#92]
Hi,

Putting this here in case it helps anyone.

When I run `micromamba env create -f CondaEnvironment_linux.yml` (adapted from the compilation instructions, using micromamba instead of conda), I get an error:

```
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ libboost 1.67.0 h46d08c1_4 is not installable because it conflicts with any installable versions previously reported.
critical libmamba Could not solve for environment specs
```

This turned out to be because I had `channel_priority: strict` in my `~/.condarc`. Removing that fixed the issue. Alternatively, you can run `micromamba env create -f CondaEnvironment_linux.yml --channel-priority flexible`.

I found that I could get GraphAligner to compile only pinning three versions, using the following `environment.yml`:
```yaml
name: GraphAligner
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - abseil-cpp
  - libboost=1.73.0=h28710b8_12
  - gxx=12.3
  - jemalloc=5.2.0
  - protobuf
  - libprotobuf-static
  - sdsl-lite
  - pkg-config
  - sparsehash
  - zlib
```

Eventually it would be nice to get GraphAligner to compile without these version pins. It should be relatively straightforward:
1. To allow compilation with GCC 13, `#include <cstdint>` must be added, otherwise g++ gives me `error: 'uint32_t' has not been declared`.
2. Convince the conda-forge `boost` maintainers to add a new `libboost-static` package or include static libraries in `libboost-devel` (https://github.com/conda-forge/boost-feedstock/issues/159). The above version pin uses `libboost` from the `anaconda` channel instead of `conda-forge`, which does include static libs.
3. Contribute a (one-line?) PR to re-enable static libraries in the conda-forge `jemalloc` package (https://github.com/conda-forge/jemalloc-feedstock/issues/24).
